### PR TITLE
Shorten default shm_monitoring_domain to avoid path length problems o…

### PR DESCRIPTION
**Pull request by KerstinKeller**
…n MacOS.

Please check the type of change your PR introduces:
- [x] Bugfix

Cherry-Pick to:
- 5.12

### CODE REVIEW

**Comment by FlorianReimold** [comment]
Is that enough? If it is, then this will obviously get my approval

**Comment by hannemn** [comment]
Only as a remark: This option only influences the name prefix of the shared memory files that are used for shared memory **monitoring** and has no effect on the file names where the acutual payloads become tranfered.

**Comment by FlorianReimold** [comment]
Yes, but as I understood, that also was the only issue, right? we already reduced the path length for the payload and event SHM files some time ago

**Comment by KerstinKeller** [comment]
@hannemn are you sure? From the code it seems that every opened memory file for the monitoring will hold the prefix.
Eg it tried to open ecal_monitoring_1394252728 (some ultraling hash) resulting in 33 or 36 chars. Shortening to ecal_mon then gives the a length <31 chars

**Review by FlorianReimold — APPROVED** [review]

**Comment by hannemn** [comment]
Okay, I tought the shared memory file names of payload and event are even longer. But if this was fixed already some time ago, then your code adaptions should solve the name length issue good enough.

**Review by hannemn — APPROVED** [review]
LGTM

**Pull request merged**
