### PR TITLE
Introducing the attribute "host group name" that allows interprocess communication across host borders

### PR DESCRIPTION
**Pull request by hannemn**
**Pull request type**

 

 

Please check the type of change your PR introduces:
- [ ] Bugfix
- [x] Feature
- [ ] Code style update (formatting, renaming)
- [ ] Refactoring (no functional changes, no api changes)
- [ ] Build related changes
- [ ] Documentation content changes
- [ ] Other (please describe): 

**What is the current behavior?**

Issue Number: #1132 

**What is the new behavior?**

The PR introduces a new setting called `host group name` to enable interprocess communication between docker containers with different host names. The `host group name` setting in ecal.ini can be configured to an abitrary string by the user. Hosts or rather containers that shares the same `host group name` are allowed to exchange data via ipc mechanisms even if there are not on the same (virtual) host. By default the local `host name` will be set as `host group name` if the respective configuration section was left empty in ecal.ini.

**Does this introduce a breaking change?**

- [ ] Yes
- [X] No

**Other information**

### CODE REVIEW

**Review by KerstinKeller — COMMENTED** [review]
Do you really want to put it in the experimental ini file group?
Everything else (at least the API) ist stable / fix anyways...
I think I'd just put it in the ini in a regular section.

**Comment by hannemn** [comment]
Yes, good point! I was a bit too pessimistic putting it into the productive config section. ;-) I will move it.

**Comment by FlorianReimold** [comment]
I am wondering whether the Host Group Name should actually be in the `ecal.ini`. If using Docker, you will probably want to set the host group name from the outside, e.g. via an environment variable. The same goes for the (actual) hostname, which is also controlled from the outside and not by an `ecal.ini` setting. Having the HostGroupName statically configured in the `ecal.ini` will prevent you from pre-configuring a docker container with libecal_core.so + custom software + ecal.ini, as you would have to know at docker compose time where the docker container is going to run.

**Review by KerstinKeller — APPROVED** [review]
Good work, Kristof  👍

**Pull request merged**
