### PR TITLE
[core] registration-loopback-logic-fixed-for-service-registrations

### PR DESCRIPTION
**Pull request by rex-schilasky**
### Description
* loopback logic (EnabledLoopback) was ignored for service registration
* some refactoring of the logic whether to process a sample registration or not
* user registration callback performance fix
  * samples will be reserialized only if the corresponding callback is set

### CODE REVIEW

**Review by KerstinKeller — COMMENTED** [review]
I think in general this is a good cleanup.
However I want to mention that we still have the following "problems":

- Callbacks are always applied, not only if `ShouldProcessRegistration()==true`. Do we want that behavior? Should the user be informed of a publisher, that he would never receive data from, even if he created a publisher for it?
- Same for monitoring / descgate map. Feels wrong to have information available, if they are not applicable for the process. OR we should additional save the information e.g. it appears in the monitoring but we can see from the settings / another flag that this process won't be able to receive data from this entity because of the current configuration.

**Comment by rex-schilasky** [comment]
> * Callbacks are always applied, not only if `ShouldProcessRegistration()==true`. Do we want that behavior? Should the user be informed of a publisher, that he would never receive data from, even if he created a publisher for it?

No, that is not the wanted behavior. I will check for this and figure out how to fix this too. Thank you :-)

**Review by KerstinKeller — APPROVED** [review]

**Comment by KerstinKeller** [comment]
@rex-schilasky Take a look at the last commit, I think we can merge it like this.

**Comment by rex-schilasky** [comment]
> @rex-schilasky Take a look at the last commit, I think we can merge it like this.

LGTM, Danke :-)

**Pull request merged**
