### PR TITLE
GH Actions: Switched MacOS to C++17 and latest protobuf again

### PR DESCRIPTION
**Pull request by FlorianReimold**

### CODE REVIEW

**Review by KerstinKeller — CHANGES_REQUESTED** [review]
@FlorianReimold did you again change the hdf5 submodule?

**Comment by KerstinKeller** [comment]
I would try to also provide `-DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON`

**Comment by FlorianReimold** [comment]
> did you again change the hdf5 submodule?

Oopsi!

> I would try to also provide `-DCMAKE_FIND_PACKAGE_PREFER_CONFIG=ON`

Let's try!

**Comment by FlorianReimold** [comment]
Current compile issue seems to come from an API change of the protobuf JSON parser:

```
[1186/1287] Building CXX object samples/cpp/services/ping_client_dyn/CMakeFiles/ping_client_dyn.dir/src/proto_json_conv.cpp.o
FAILED: samples/cpp/services/ping_client_dyn/CMakeFiles/ping_client_dyn.dir/src/proto_json_conv.cpp.o 
/Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -DASIO_DISABLE_VISIBILITY -DASIO_STANDALONE -DPROTOBUF_USE_DLLS -I/Users/runner/work/ecal/ecal/ecal/core/include -I/Users/runner/work/ecal/_build/ecal/core/include -I/Users/runner/work/ecal/ecal/contrib/ecalproto/include -isystem /usr/local/include -O3 -DNDEBUG -std=gnu++17 -isysroot /Applications/Xcode_14.2.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX13.1.sdk -mmacosx-version-min=12.6   -Wall -Wextra -F/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk/System/Library/Frameworks -MD -MT samples/cpp/services/ping_client_dyn/CMakeFiles/ping_client_dyn.dir/src/proto_json_conv.cpp.o -MF samples/cpp/services/ping_client_dyn/CMakeFiles/ping_client_dyn.dir/src/proto_json_conv.cpp.o.d -o samples/cpp/services/ping_client_dyn/CMakeFiles/ping_client_dyn.dir/src/proto_json_conv.cpp.o -c /Users/runner/work/ecal/ecal/samples/cpp/services/ping_client_dyn/src/proto_json_conv.cpp
/Users/runner/work/ecal/ecal/samples/cpp/services/ping_client_dyn/src/proto_json_conv.cpp:36:27: error: no type named 'Status' in namespace 'google::protobuf::util'
  google::protobuf::util::Status status = google::protobuf::util::JsonStringToMessage(msg_json_, msg_proto_);
  ~~~~~~~~~~~~~~~~~~~~~~~~^
/Users/runner/work/ecal/ecal/samples/cpp/services/ping_client_dyn/src/proto_json_conv.cpp:63:27: error: no type named 'Status' in namespace 'google::protobuf::util'
  google::protobuf::util::Status status = google::protobuf::util::MessageToJsonString(*msg_proto_, &msg_json);
  ~~~~~~~~~~~~~~~~~~~~~~~~^
2 errors generated.
```

Protobuf v22 has replaced the JSON Parser with a new implementation:
https://github.com/protocolbuffers/protobuf/releases/tag/v22.0

**Review by KerstinKeller — APPROVED** [review]
I think it should build now.

**Comment by FlorianReimold** [comment]
Oh, that doesn't look too difficult! Shall we also cherry pick it to 5.12? What do you think?

**Pull request merged**
